__all__ = ['additional_complexified_examples_tests',
           'test_block_partition',
           'test_block_smooth_convex_functions',
           'test_constraints',
           'test_dict_operations',
           'test_examples',
           'test_expression',
           'test_expression_to_matrices',
           'test_function',
           'test_functions_and_operators',
           'test_pep',
           'test_point',
           'test_psd_matrix',
           'test_uselessly_complexified_examples',
           'test_wrappers',
           ]
