__all__ = ['accelerated_douglas_rachford_splitting',
           'bregman_proximal_point_method',
           'conditional_gradient_frank_wolfe',
           'douglas_rachford_splitting_1',
           'douglas_rachford_splitting_2',
           'fast_proximal_gradient_method',
           'improved_interior_algorithm',
           'no_lips_1',
           'no_lips_2',
           'proximal_gradient',
           'three_operator_splitting',
           ]
