__all__ = ['conjugate_gradient_method',
           'fast_gradient_method',
           'fast_gradient_method_strongly_convex',
           'fast_proximal_point',
           'gradient_descent',
           'gradient_exact_line_search',
           'heavy_ball_method',
           'inexact_accelerated_gradient',
           'inexact_gradient_descent',
           'inexact_gradient_exact_line_search',
           'optimized_gradient_method',
           'proximal_point_method',
           'robust_momentum_method',
           'subgradient_method',
           'triple_momentum_method',
           ]
